# Generated by Django 3.0 on 2021-10-22 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_auto_20211022_1222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='user',
            new_name='student',
        ),
    ]
