# Generated by Django 3.0 on 2021-10-22 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_auto_20211022_1452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='student',
            new_name='author',
        ),
    ]
