# Generated by Django 3.0 on 2021-10-31 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_auto_20211022_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answertoquestion',
            name='title',
            field=models.TextField(),
        ),
    ]
