# Generated by Django 3.0 on 2021-11-05 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_auto_20211031_1411'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answertoquestion',
            options={'ordering': ['-created']},
        ),
    ]
