# Generated by Django 3.0 on 2021-09-15 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20210912_0840'),
        ('courses', '0004_auto_20210915_0808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursereview',
            name='user',
        ),
        migrations.AddField(
            model_name='coursereview',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='groups.Student'),
            preserve_default=False,
        ),
    ]
