# Generated by Django 3.0 on 2021-09-16 17:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0007_course_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursereview',
            name='dislikes',
        ),
        migrations.AddField(
            model_name='coursereview',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='review_disliked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='coursereview',
            name='likes',
        ),
        migrations.AddField(
            model_name='coursereview',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='review_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
