# Generated by Django 3.0 on 2021-10-22 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0008_auto_20211022_1452'),
        ('courses', '0008_auto_20210916_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(related_name='students', to='groups.Student'),
        ),
    ]
