# Generated by Django 3.0 on 2021-11-05 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0010_auto_20211105_0723'),
        ('courses', '0009_auto_20211022_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_teachers', to='groups.Teacher'),
        ),
    ]
