# Generated by Django 3.0 on 2021-11-20 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0015_human_number'),
        ('courses', '0012_course_time_to_support_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category_by_skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.CategoryBySkill'),
        ),
        migrations.AlterField(
            model_name='course',
            name='category_by_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.CategoryByType'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='course',
            name='hourse',
            field=models.IntegerField(default=0, verbose_name='Кол-во часов'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='students', to='groups.Student'),
        ),
        migrations.AlterField(
            model_name='course',
            name='time_to_support_course',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='views',
            field=models.IntegerField(default=0, verbose_name='кол-во просмотров'),
        ),
    ]
