# Generated by Django 3.0 on 2021-11-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0015_human_number'),
        ('courses', '0013_auto_20211120_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, related_name='students', to='groups.Student'),
        ),
    ]
