# Generated by Django 3.0 on 2021-10-29 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_messages', '0002_auto_20211029_0734'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialogue',
            name='new_msg_count',
            field=models.IntegerField(default=0),
        ),
    ]
