# Generated by Django 3.0 on 2021-11-05 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0010_auto_20211105_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='human',
            name='show_courses',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='human',
            name='show_profile',
            field=models.BooleanField(default=True),
        ),
    ]
