# Generated by Django 3.0 on 2021-11-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0012_human_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='country',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='language',
        ),
        migrations.AddField(
            model_name='human',
            name='country',
            field=models.CharField(blank=True, max_length=255, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='human',
            name='language',
            field=models.CharField(blank=True, max_length=255, verbose_name='Язык'),
        ),
    ]
