# Generated by Django 3.0 on 2021-11-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0014_auto_20211115_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='human',
            name='number',
            field=models.TextField(blank=True, null=True),
        ),
    ]
